---
- name: Ensure fish is installed
  community.general.homebrew:
    name: fish
    path: "{{ brew_bin_location }}"

- name: Backup default bash files and .profile
  ansible.builtin.include_tasks: backup_file.yml
  loop:
    - ~/.profile
    - ~/.bashrc
    - ~/.bash_login

# XXX(andrea): should we use XDG_CONFIG_HOME instead of hardcoding ~/.config?
# XXX(andrea): what if the XDG_CONFIG_HOME variable is not set? does ansible see it?
- name: Ensure ~/.config directory exists.
  ansible.builtin.file:
    path: "~/.config"
    state: directory
    mode: '0755'

- name: Link fish configuration.
  ansible.builtin.file:
    src: "{{ role_path }}/files/fish"
    path: "~/.config/fish"
    state: link

- name: Link .profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/.profile"
    path: ~/.profile
    state: link
  when: not is_macOS

- name: Change default shell to fish-shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ brew_bin_location }}/fish"
  become: true
  when: is_macOS
