---
- name: Backup default bash files and .profile
  include_tasks: backup_file.yml
  loop:
    - ~/.profile
    - ~/.bashrc
    - ~/.bash_login

- name: Link .profile
  file:
    src: "{{ role_path }}/files/.profile"
    path: ~/.profile
    state: link

# XXX(andrea): should we use XDG_CONFIG_HOME instead of hardcoding ~/.config?
# XXX(andrea): what if the XDG_CONFIG_HOME variable is not set? does ansible see it?
- name: Ensure ~/.config directory exists.
  file:
    path: "~/.config"
    state: directory

- name: Link fish configuration.
  file:
    src: "{{ role_path }}/files/fish"
    path: "~/.config/fish"
    state: link

# XXX(andrea): right now we're hardcoding the path for the M1 mac. We should
# make the brew variable global so that we can reuse it here also.
- name: Change default shell to fish-shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /opt/homebrew/bin/fish
  become: yes
  when: is_macOS
