---
# Variable configuration.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}_{{ ansible_architecture }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure fish is installed.
  ansible.builtin.include_tasks: "install_{{ ansible_os_family }}.yml"

- name: Backup default bash files and .profile
  ansible.builtin.include_tasks: backup_file.yml
  loop:
    - ~/.profile
    - ~/.bashrc
    - ~/.bash_login

# XXX(andrea): should we use XDG_CONFIG_HOME instead of hardcoding ~/.config?
# XXX(andrea): what if the XDG_CONFIG_HOME variable is not set? does ansible see it?
- name: Ensure ~/.config directory exists.
  ansible.builtin.file:
    path: "~/.config"
    state: directory
    mode: '0755'

- name: Link fish configuration.
  ansible.builtin.file:
    src: "{{ role_path }}/files/fish"
    path: "~/.config/fish"
    state: link

- name: Change default shell to fish-shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_binary_location }}"
  become: true
