#!/usr/bin/env ansible-playbook
---
- hosts: all
  connection: local

  pre_tasks:
    - name: Check if ~/.provision_profile exists.
      stat:
        path: "~/.provision_profile"
      register: provision_profile_file_stat
      tags:
        - always

    - block:
      - name: Detect if the work profile for this machine was already chosen
        lineinfile:
          path: "~/.provision_profile"
          line: 'work'
          state: present
        check_mode: yes
        register: provision_profile

      - set_fact:
          on_work_machine: "{{ not provision_profile.changed }}"

      when: provision_profile_file_stat.stat.exists
      tags:
        - always

    - block:
      - pause:
          prompt: Is this a work machine?
        register: prompt_work_machine
      - set_fact:
          on_work_machine: "{{ prompt_work_machine.user_input | bool }}"

      - name: Save the chosen profile
        lineinfile:
          path: "~/.provision_profile"
          line: "{{ on_work_machine | ternary('work', 'nonwork') }}"
          state: present
          create: yes

      when: not provision_profile_file_stat.stat.exists
      tags:
        - always

    - name: Detect if on macOS
      set_fact:
        is_macOS: "{{ansible_os_family | lower == 'darwin'}}"
      tags:
        - always


  roles:
    # XXX(andrea): add tags on roles so we can run specific section of the configuration
    - role: machine
      tags:
        - machine
      when: not is_macOS
    - role: compiler
      tags:
        - compiler
      when: not is_macOS
    - role: homebrew
      tags:
        - homebrew
    - role: tmux
    - role: fish
    - role: git
    - role: ssh
    - role: go
    - role: neovim
    - role: geerlingguy.docker
      vars:
        docker_install_compose: false # We might want to install docker-compose through brew
        docker_users:
          - "{{ lookup('env', 'USER') }}"
      become: yes
      when: not is_macOS
      tags:
        - docker
    - role: libvirt
      when: not is_macOS
      tags:
        - libvirt
    # XXX(andrea): right now this will contains only vagrant for Linux but we
    # should move `libvirt` and `docker` to this role since they are all
    # related to the same use case for me.
    - role: virtualization
      when: not is_macOS
      tags:
        - virtualization
    # XXX(andrea): next steps to implement
    # - role: macOS
    # - role: karabiner-elements
    # - role: iTerm2
    # - role: hammerspoon??
