#!/usr/bin/env ansible-playbook
---
- hosts: all
  connection: local

  vars_prompt:
    - name: workMachine
      prompt: Is this a work machine?
      private: no
      default: false

  pre_tasks:
    - name: Detect if on macOS
      set_fact:
        is_macOS: "{{ansible_os_family | lower == 'darwin'}}"

    - name: Detect if work machine
      set_fact:
        onWorkMachine: "{{ workMachine | bool }}"

  roles:
    # XXX(andrea): add tags on roles so we can run specific section of the configuration
    - role: homebrew
    - role: tmux
    - role: fish
    - role: git
    - role: ssh
    - role: go
    - role: neovim
    - role: geerlingguy.docker
      vars:
        docker_install_compose: false # We might want to install docker-compose through brew
        docker_users:
          - "{{ lookup('env', 'USER') }}"
      become: yes
      when: not is_macOS
    # XXX(andrea): next steps to implement
    # - role: macOS
    # - role: karabiner-elements
    # - role: iTerm2
    # - role: hammerspoon??
