#!/usr/bin/env ansible-playbook
---
- hosts: all
  connection: local

  pre_tasks:
    - name: Check if ~/.provision_profile exists.
      ansible.builtin.stat:
        path: "~/.provision_profile"
      register: provision_profile_file_stat
      tags:
        - always

    - block:
      - name: Detect if the work profile for this machine was already chosen
        ansible.builtin.lineinfile:
          path: "~/.provision_profile"
          line: 'work'
          state: present
        check_mode: true
        register: provision_profile

      - set_fact:
          on_work_machine: "{{ not provision_profile.changed }}"

      when: provision_profile_file_stat.stat.exists
      tags:
        - always

    - block:
      - pause:
          prompt: Is this a work machine?
        register: prompt_work_machine
      - set_fact:
          on_work_machine: "{{ prompt_work_machine.user_input | bool }}"

      - name: Save the chosen profile
        lineinfile:
          path: "~/.provision_profile"
          line: "{{ on_work_machine | ternary('work', 'nonwork') }}"
          state: present
          create: true

      when: not provision_profile_file_stat.stat.exists
      tags:
        - always

    - name: Detect if on macOS
      set_fact:
        # XXX(andrea): I hate this name... maybe just "macOS" or simply "macbook"
        is_macOS: "{{ ansible_os_family | lower == 'darwin' }}"
      tags:
        - always

    - include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_os_family }}_{{ ansible_architecture }}.yml"
        - "{{ ansible_os_family }}.yml"
      tags:
        - always

  roles:
    # XXX(andrea): add tags on roles so we can run specific section of the configuration
    - role: machine
      tags:
        - machine
      when: not is_macOS
    - role: compiler
      tags:
        - compiler
      when: not is_macOS
    - role: homebrew
      tags:
        - homebrew
    - role: tmux
    - role: fish
    - role: git
      tags:
        - git
    - role: ssh
      tags:
        - ssh
    - role: go
    - role: neovim
      tags:
        - neovim
    - role: virtualization
      when: not is_macOS
      tags:
        - virtualization
    - role: karabiner
      when: is_macOS
      tags:
        - karabiner
    - role: iterm
      when: is_macOS
      tags:
        - iterm
    - role: hammerspoon
      when: is_macOS
      tags:
        - hammerspoon
    # XXX(andrea): next steps to implement
    # - role: macOS
