#!/bin/bash

# If we already have the password store in a variable for the current session
# just print that and exit so that we don't hit the keychain every time.

if [[ ! -z $ANSIBLE_VAULT_PASSWORD ]]; then
  echo $ANSIBLE_VAULT_PASSWORD
  exit 0
fi

if ! command -v /usr/bin/security &> /dev/null
then
  # if /usr/bin/security is not present it means that we do not actually need
  # any password so print nothing and exit
  echo ""
  exit 0
fi

/usr/bin/security find-generic-password -w -a "vheon" -l "ansible-vault-dotfiles"
