---
# XXX(andrea): right now I'm using this only for a simple configuration but as
# soon as I start adding stuff there I should encrypt the file.
- name: Link ssh config file
  file:
    src: "{{ role_path }}/files/config"
    path: ~/.ssh/config
    state: link
  when: on_work_machine
