---
- name: Ensure git is installed
  become: true
  block:
    - name: Add git-core repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:git-core/ppa

    - name: Install git
      ansible.builtin.apt:
        name:
          - git
        state: present
