---
- name: Ensure git is installed through brew to get an up to date version
  community.general.homebrew:
    name: git
    path: "{{ brew_bin_location }}"

- name: Create global .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Link .cvsignore file
  file:
    src: "{{ role_path }}/files/.cvsignore"
    path: "~/.cvsignore"
    state: link
