---
- name: Create global .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Link .cvsignore file
  file:
    src: "{{ role_path }}/files/.cvsignore"
    path: "~/.cvsignore"
    state: link
