- name: Ensure git, curl and gcc are installed in the system.
  package:
    name:
      - git
      - curl
      - gcc
      - make
    state: present
  become: true
  when: ansible_os_family | lower != 'darwin'
