- name: Check if brew is not already installed.
  shell: command -v brew # > /dev/null 2>&1
  register: brew_installed
  ignore_errors: yes

- debug:
    msg: "cmd: {{ brew_installed.cmd }}; rc: {{brew_installed.rc}}; stderr: {{brew_installed.stderr}}; stdout: {{brew_installed.stdout}}"

- name: Install Homebrew.
  script: install.sh
  when: brew_installed.rc | int != 0

