- include_tasks: homebrew_prerequisite.yml
- include_tasks: install_homebrew.yml

- name: Create the global ~/.Brewfile
  template:
    src: Brewfile.j2
    dest: ~/.Brewfile

# - name: Install all from Brewfile and remove all the rest.
#   shell: >
#     echo {{ lookup('template', 'Brewfile.j2') }} |
#     brew bundle install --file=- --cleanup
- name: Install all from Brewfile and remove all the rest.
  shell: echo $HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK && brew bundle install --global --cleanup
  environment:
    HOMEBREW_NO_COLOR: 1
