- include_tasks: homebrew_prerequisite.yml
- include_tasks: install_homebrew.yml

- name: Create the global ~/.Brewfile
  ansible.builtin.template:
    src: Brewfile.j2
    dest: ~/.Brewfile
    mode: '0644'
  register: brewfile

- name: Install all from Brewfile and remove all the rest.
  ansible.builtin.shell: "{{brew_binary}} bundle install --no-lock --global --cleanup"
  environment:
    HOMEBREW_NO_COLOR: "1"
    PATH: "{{brew_bin_location}}:{{ ansible_env.PATH }}"
  when: brewfile.changed
