---
- name: Ensure Wezterm is installed
  ansible.builtin.include_tasks: "install_{{ ansible_os_family }}.yml"

- name: Configure Wezterm
  when: is_macOS
  block:
    - name: Ensure ~/.config directory exists
      ansible.builtin.file:
        path: "~/.config"
        state: directory
        mode: '0755'

    - name: Link configuration in XDG_CONFIG_HOME
      ansible.builtin.file:
        src: "{{ role_path }}/files/wezterm"
        path: "~/.config/nvim"
        state: link
