- name: Ensure tmux is installed
  community.general.homebrew:
    name: tmux
    path: "{{ brew_bin_location }}"

- name: Link tmux configuration.
  ansible.builtin.file:
    src: "{{ role_path }}/files/.tmux.conf"
    path: "~/.tmux.conf"
    state: link
