---
- name: Add hashicorp apt GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
  become: true

- name: Add hashicorp repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main
    state: present
  become: true

# XXX(andrea): I don't remember why these are not pulled from brew :/
- name: Install Vagrant and virtualization dependencies
  apt:
    name:
      - vagrant
      - qemu
      - qemu-kvm
      - libvirt-daemon
      - libvirt-clients
      - bridge-utils
      - virt-manager
    state: present
  become: true

- name: Enable libvirtd service
  service:
    name: libvirtd
    enabled: yes
    state: restarted
  become: true

- name: Install docker python package
  ansible.builtin.pip:
    name: docker

- name: Pull the vagrant-libvirt image
  community.docker.docker_image:
    name: vagrantlibvirt/vagrant-libvirt:edge
    source: pull

- name: Link vagrant wrapper for the fish shell
  file:
    src: vagrant.fish
    path: "~/.local/share/fish/vagrant.fish"
    state: link

- name: Install Hashicorp Packer in order to create various images
  community.general.homebrew:
    name: packer
    path: "{{ brew_bin_location }}"
