---
- name: Add hashicorp apt GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
  become: true

- name: Add hashicorp repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main
    state: present
  become: true

# XXX(andrea): I don't remember why these are not pulled from brew :/
- name: Install Vagrant and virtualization dependencies
  apt:
    name:
      - vagrant
      - qemu
      - qemu-kvm
      - libvirt-daemon
      - libvirt-clients
      - bridge-utils
      - virt-manager
    state: present
  become: true

- name: Enable libvirtd service
  service:
    name: libvirtd
    enabled: yes
    state: restarted
  become: true

- name: Install docker python package
  ansible.builtin.pip:
    name: docker

- name: Pull the vagrant-libvirt image
  community.docker.docker_image:
    name: vagrantlibvirt/vagrant-libvirt:latest
    source: pull

- name: Install vagrant fish wrapper
  block:
  - name: Ensure XDG_DATA_HOME/fish/vendor_functions.d directory exists.
    file:
      path: "~/.local/share/fish/vendor_functions.d"
      state: directory

  - name: Link vagrant wrapper for the fish shell
    file:
      src: "{{ role_path }}/files/vagrant.fish"
      path: "~/.local/share/fish/vendor_functions.d/vagrant.fish"
      state: link

- name: Install Hashicorp Packer in order to create various images
  community.general.homebrew:
    name: packer
    path: "{{ brew_bin_location }}"

- name: Install LXD
  community.general.snap:
    name:
      - lxd
    channel: latest/stable

# XXX(andrea): the whole lxd init is missing still
# XXX(andrea): also a lot of the settings in https://github.com/lxc/lxd/blob/master/doc/production-setup.md should be applied
