---
- name: Set sysctl File Limits
  ansible.builtin.copy:
    src: 50-fs.conf
    dest: /etc/sysctl.d
    mode: '0644'
  become: true

- name: Set Shell File Limits
  ansible.builtin.copy:
    src: 91-nofiles.conf
    dest: /etc/security/limits.d
    mode: '0644'
  become: true
