---
- name: Change machine configuration
  become: true
  block:
    - name: Set sysctl File Limits
      ansible.posix.sysctl:
        name: fs.file-max
        value: '262144'
        state: present

    - name: Set kernel option for perf events
      ansible.posix.sysctl:
        name: kernel.perf_event_paranoid
        value: '-1'
        state: present

    - name: Set Shell File Limits
      ansible.builtin.copy:
        src: 91-nofiles.conf
        dest: /etc/security/limits.d
        mode: '0644'
