---
- name: Ensure iTerm2 DynamicProfiles directory exists.
  file:
    path: ~/Library/Application Support/iTerm2/DynamicProfiles
    state: directory

- name: Create Base Dynamic Profile
  template:
    src: 00-Base.json.j2
    dest: "~/Library/Application Support/iTerm2/DynamicProfiles/00-Base.json"

- name: Link Local Dynamic Profile
  file:
    src: "{{ role_path }}/files/DynamicProfiles/20-Local-Retina.json"
    path: "~/Library/Application Support/iTerm2/DynamicProfiles/20-Local.json"
    state: link
