---
- name: Ensure iTerm2 and the configured font are installed
  community.general.homebrew_cask:
    name:
      - iterm2-beta
      - font-jetbrains-mono-nerd-font
    path: "{{ brew_bin_location }}"

- name: Ensure iTerm2 DynamicProfiles directory exists.
  file:
    path: ~/Library/Application Support/iTerm2/DynamicProfiles
    state: directory

- name: Create Base Dynamic Profile
  template:
    src: 00-Base.json.j2
    dest: "~/Library/Application Support/iTerm2/DynamicProfiles/00-Base.json"

- name: Link Local Dynamic Profile
  file:
    src: "{{ role_path }}/files/DynamicProfiles/20-Local-Retina.json"
    path: "~/Library/Application Support/iTerm2/DynamicProfiles/20-Local.json"
    state: link

- name: Ensure iTerm2 Scripts directory exists.
  file:
    path: "~/Library/Application Support/iTerm2/Scripts"
    state: directory

- name: Link scripts
  file:
    src: "{{ role_path }}/files/Scripts/adjust_font_size.py"
    path: "~/Library/Application Support/iTerm2/Scripts/adjust_font_size.py"
    state: link

