---
- name: Ensure neovim is install
  community.general.homebrew:
    name: neovim-nightly
    install_options: HEAD
    path: "{{ brew_bin_location }}"

# XXX(andrea): should we use XDG_CONFIG_HOME instead of hardcoding ~/.config?
# XXX(andrea): what if the XDG_CONFIG_HOME variable is not set? does ansible see it?
# XXX(andrea): these considerations are the same as for fish
- name: Ensure ~/.config directory exists
  ansible.builtin.file:
    path: "~/.config"
    state: directory
    mode: '0755'

- name: Link configuration in XDG_CONFIG_HOME
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvim"
    path: "~/.config/nvim"
    state: link

- name: Install LSP Servers dependency
  community.general.homebrew:
    name:
      - go
      - npm
    path: "{{ brew_bin_location }}"

# XXX(andrea): should we use XDG_DATA_HOME instead of hardcoding ~/.local/share?
# XXX(andrea): I would love to mimic the instruction from lazy.nvim and pass also `--filter=blob:none`
- name: Clone package manager lazy.nvim
  ansible.builtin.git:
    dest: ~/.local/share/nvim/lazy/lazy.nvim
    repo: https://github.com/folke/lazy.nvim.git
    version: stable
    update: false

# XXX(andrea): maybe we should set the environment for the whole playbook and be done with it. We could put also XDG directories as well.
- name: Install all plugins
  ansible.builtin.command: "{{ brew_bin_location }}/nvim --headless '+Lazy! sync' +qa"
  args:
    creates: ~/.local/share/nvim/lazy/catppuccin

- name: Ensure ~/code directory exists
  ansible.builtin.file:
    path: "~/code"
    state: directory
    mode: '0755'
